### ISSUE TITLE
Conditional logic supported?

### ISSUE THREAD

**Issue by lopugit** [verbb/formie-headless#1]
Hi Verbb guys,

I've successfully implemented this starter into one of our projects. And it's a Vue 2 project so, just goes to show how good of job you guys did since it was quite easy to port back to Vue 2.

I'm just doing testing and I'm wondering if there was support added for conditional fields or if I should add that in manually, I'm sure it's not too hard but yeah I was just wondering.

Kind regards

**Comment by engram-design** [comment]
Nice to hear! So conditional fields are supported in this project. We have plans to release an npm package for Formie that'll bundle all the required useful utilities needed to make a form work. One of these utilities will be parsing and evaluating conditional logic, for you to handle as you please in your apps.

You can access a JSON-encoded string via GraphQL, and you'll need to write JS on your end to parse and evaluate them. You can see how we do this ourselves https://github.com/verbb/formie/blob/craft-3/src/web/assets/frontend/src/js/fields/conditions.js if you want to model your own logic off it. It's a tiny bit complex with the need to handle radio/checkbox fields which feature multiple values, but otherwise, the logic should be (hopefully) pretty easy to follow.

**Comment by lopugit** [comment]
> Nice to hear! So conditional fields are supported in this project. We have plans to release an npm package for Formie that'll bundle all the required useful utilities needed to make a form work. One of these utilities will be parsing and evaluating conditional logic, for you to handle as you please in your apps.
> 
> You can access a JSON-encoded string via GraphQL, and you'll need to write JS on your end to parse and evaluate them. You can see how we do this ourselves https://github.com/verbb/formie/blob/craft-3/src/web/assets/frontend/src/js/fields/conditions.js if you want to model your own logic off it. It's a tiny bit complex with the need to handle radio/checkbox fields which feature multiple values, but otherwise, the logic should be (hopefully) pretty easy to follow.

Thanks so much, I'll see if I can get this working!!!
